//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.huaxinMes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string po_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string s1310Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string s1550Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jyrqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jieguoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jianyanhezhunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string beizhuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string s1383Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yanseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pmdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string s1625Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string po_no {
            get {
                return this.po_noField;
            }
            set {
                if ((object.ReferenceEquals(this.po_noField, value) != true)) {
                    this.po_noField = value;
                    this.RaisePropertyChanged("po_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string len {
            get {
                return this.lenField;
            }
            set {
                if ((object.ReferenceEquals(this.lenField, value) != true)) {
                    this.lenField = value;
                    this.RaisePropertyChanged("len");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string s1310 {
            get {
                return this.s1310Field;
            }
            set {
                if ((object.ReferenceEquals(this.s1310Field, value) != true)) {
                    this.s1310Field = value;
                    this.RaisePropertyChanged("s1310");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string s1550 {
            get {
                return this.s1550Field;
            }
            set {
                if ((object.ReferenceEquals(this.s1550Field, value) != true)) {
                    this.s1550Field = value;
                    this.RaisePropertyChanged("s1550");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string jyrq {
            get {
                return this.jyrqField;
            }
            set {
                if ((object.ReferenceEquals(this.jyrqField, value) != true)) {
                    this.jyrqField = value;
                    this.RaisePropertyChanged("jyrq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string jieguo {
            get {
                return this.jieguoField;
            }
            set {
                if ((object.ReferenceEquals(this.jieguoField, value) != true)) {
                    this.jieguoField = value;
                    this.RaisePropertyChanged("jieguo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string jianyanhezhun {
            get {
                return this.jianyanhezhunField;
            }
            set {
                if ((object.ReferenceEquals(this.jianyanhezhunField, value) != true)) {
                    this.jianyanhezhunField = value;
                    this.RaisePropertyChanged("jianyanhezhun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string beizhu {
            get {
                return this.beizhuField;
            }
            set {
                if ((object.ReferenceEquals(this.beizhuField, value) != true)) {
                    this.beizhuField = value;
                    this.RaisePropertyChanged("beizhu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string s1383 {
            get {
                return this.s1383Field;
            }
            set {
                if ((object.ReferenceEquals(this.s1383Field, value) != true)) {
                    this.s1383Field = value;
                    this.RaisePropertyChanged("s1383");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string yanse {
            get {
                return this.yanseField;
            }
            set {
                if ((object.ReferenceEquals(this.yanseField, value) != true)) {
                    this.yanseField = value;
                    this.RaisePropertyChanged("yanse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pmd {
            get {
                return this.pmdField;
            }
            set {
                if ((object.ReferenceEquals(this.pmdField, value) != true)) {
                    this.pmdField = value;
                    this.RaisePropertyChanged("pmd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string s1625 {
            get {
                return this.s1625Field;
            }
            set {
                if ((object.ReferenceEquals(this.s1625Field, value) != true)) {
                    this.s1625Field = value;
                    this.RaisePropertyChanged("s1625");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dingdan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class dingdan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dingdanhaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xiangciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kuhudmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kuhumcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string liaohaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string chanpmcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dinggourqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jiaohuorqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dinghuolenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jiaohuolenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string huobiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gongdanhaomaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yanseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dinggouyaoqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string suoshuquyuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hetonghaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dingdanhao {
            get {
                return this.dingdanhaoField;
            }
            set {
                if ((object.ReferenceEquals(this.dingdanhaoField, value) != true)) {
                    this.dingdanhaoField = value;
                    this.RaisePropertyChanged("dingdanhao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xiangci {
            get {
                return this.xiangciField;
            }
            set {
                if ((object.ReferenceEquals(this.xiangciField, value) != true)) {
                    this.xiangciField = value;
                    this.RaisePropertyChanged("xiangci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string kuhudm {
            get {
                return this.kuhudmField;
            }
            set {
                if ((object.ReferenceEquals(this.kuhudmField, value) != true)) {
                    this.kuhudmField = value;
                    this.RaisePropertyChanged("kuhudm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string kuhumc {
            get {
                return this.kuhumcField;
            }
            set {
                if ((object.ReferenceEquals(this.kuhumcField, value) != true)) {
                    this.kuhumcField = value;
                    this.RaisePropertyChanged("kuhumc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string liaohao {
            get {
                return this.liaohaoField;
            }
            set {
                if ((object.ReferenceEquals(this.liaohaoField, value) != true)) {
                    this.liaohaoField = value;
                    this.RaisePropertyChanged("liaohao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string chanpmc {
            get {
                return this.chanpmcField;
            }
            set {
                if ((object.ReferenceEquals(this.chanpmcField, value) != true)) {
                    this.chanpmcField = value;
                    this.RaisePropertyChanged("chanpmc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dinggourq {
            get {
                return this.dinggourqField;
            }
            set {
                if ((object.ReferenceEquals(this.dinggourqField, value) != true)) {
                    this.dinggourqField = value;
                    this.RaisePropertyChanged("dinggourq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string jiaohuorq {
            get {
                return this.jiaohuorqField;
            }
            set {
                if ((object.ReferenceEquals(this.jiaohuorqField, value) != true)) {
                    this.jiaohuorqField = value;
                    this.RaisePropertyChanged("jiaohuorq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string dinghuolen {
            get {
                return this.dinghuolenField;
            }
            set {
                if ((object.ReferenceEquals(this.dinghuolenField, value) != true)) {
                    this.dinghuolenField = value;
                    this.RaisePropertyChanged("dinghuolen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string jiaohuolen {
            get {
                return this.jiaohuolenField;
            }
            set {
                if ((object.ReferenceEquals(this.jiaohuolenField, value) != true)) {
                    this.jiaohuolenField = value;
                    this.RaisePropertyChanged("jiaohuolen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string jine {
            get {
                return this.jineField;
            }
            set {
                if ((object.ReferenceEquals(this.jineField, value) != true)) {
                    this.jineField = value;
                    this.RaisePropertyChanged("jine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string huobi {
            get {
                return this.huobiField;
            }
            set {
                if ((object.ReferenceEquals(this.huobiField, value) != true)) {
                    this.huobiField = value;
                    this.RaisePropertyChanged("huobi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string gongdanhaoma {
            get {
                return this.gongdanhaomaField;
            }
            set {
                if ((object.ReferenceEquals(this.gongdanhaomaField, value) != true)) {
                    this.gongdanhaomaField = value;
                    this.RaisePropertyChanged("gongdanhaoma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string yanse {
            get {
                return this.yanseField;
            }
            set {
                if ((object.ReferenceEquals(this.yanseField, value) != true)) {
                    this.yanseField = value;
                    this.RaisePropertyChanged("yanse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string dinggouyaoq {
            get {
                return this.dinggouyaoqField;
            }
            set {
                if ((object.ReferenceEquals(this.dinggouyaoqField, value) != true)) {
                    this.dinggouyaoqField = value;
                    this.RaisePropertyChanged("dinggouyaoq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string suoshuquyu {
            get {
                return this.suoshuquyuField;
            }
            set {
                if ((object.ReferenceEquals(this.suoshuquyuField, value) != true)) {
                    this.suoshuquyuField = value;
                    this.RaisePropertyChanged("suoshuquyu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string hetonghao {
            get {
                return this.hetonghaoField;
            }
            set {
                if ((object.ReferenceEquals(this.hetonghaoField, value) != true)) {
                    this.hetonghaoField = value;
                    this.RaisePropertyChanged("hetonghao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="huaxinMes.LikuWSSoap")]
    public interface LikuWSSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 po_no 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kucunqian", ReplyAction="*")]
        WebApi.huaxinMes.kucunqianResponse kucunqian(WebApi.huaxinMes.kucunqianRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kucunqian", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.kucunqianResponse> kucunqianAsync(WebApi.huaxinMes.kucunqianRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 po_no 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kucunhou", ReplyAction="*")]
        WebApi.huaxinMes.kucunhouResponse kucunhou(WebApi.huaxinMes.kucunhouRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kucunhou", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.kucunhouResponse> kucunhouAsync(WebApi.huaxinMes.kucunhouRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dingdan 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getdingdanshuju", ReplyAction="*")]
        WebApi.huaxinMes.getdingdanshujuResponse getdingdanshuju(WebApi.huaxinMes.getdingdanshujuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getdingdanshuju", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.getdingdanshujuResponse> getdingdanshujuAsync(WebApi.huaxinMes.getdingdanshujuRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dingdan 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getxianghao", ReplyAction="*")]
        WebApi.huaxinMes.getxianghaoResponse getxianghao(WebApi.huaxinMes.getxianghaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getxianghao", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.getxianghaoResponse> getxianghaoAsync(WebApi.huaxinMes.getxianghaoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dingdan 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fahuohou", ReplyAction="*")]
        WebApi.huaxinMes.fahuohouResponse fahuohou(WebApi.huaxinMes.fahuohouRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fahuohou", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.fahuohouResponse> fahuohouAsync(WebApi.huaxinMes.fahuohouRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 pxfa 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getguangxianhao", ReplyAction="*")]
        WebApi.huaxinMes.getguangxianhaoResponse getguangxianhao(WebApi.huaxinMes.getguangxianhaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getguangxianhao", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.getguangxianhaoResponse> getguangxianhaoAsync(WebApi.huaxinMes.getguangxianhaoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 po_no 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrk", ReplyAction="*")]
        WebApi.huaxinMes.ISrkResponse ISrk(WebApi.huaxinMes.ISrkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrk", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.ISrkResponse> ISrkAsync(WebApi.huaxinMes.ISrkRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 po_no 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuhuo", ReplyAction="*")]
        WebApi.huaxinMes.ISchuhuoResponse ISchuhuo(WebApi.huaxinMes.ISchuhuoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchuhuo", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.ISchuhuoResponse> ISchuhuoAsync(WebApi.huaxinMes.ISchuhuoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 po_no 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlingliao", ReplyAction="*")]
        WebApi.huaxinMes.ISlingliaoResponse ISlingliao(WebApi.huaxinMes.ISlingliaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISlingliao", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.ISlingliaoResponse> ISlingliaoAsync(WebApi.huaxinMes.ISlingliaoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 suilingliao 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lingliaohou", ReplyAction="*")]
        WebApi.huaxinMes.lingliaohouResponse lingliaohou(WebApi.huaxinMes.lingliaohouRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lingliaohou", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApi.huaxinMes.lingliaohouResponse> lingliaohouAsync(WebApi.huaxinMes.lingliaohouRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class kucunqianRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="kucunqian", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.kucunqianRequestBody Body;
        
        public kucunqianRequest() {
        }
        
        public kucunqianRequest(WebApi.huaxinMes.kucunqianRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class kucunqianRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string po_no;
        
        public kucunqianRequestBody() {
        }
        
        public kucunqianRequestBody(string po_no) {
            this.po_no = po_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class kucunqianResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="kucunqianResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.kucunqianResponseBody Body;
        
        public kucunqianResponse() {
        }
        
        public kucunqianResponse(WebApi.huaxinMes.kucunqianResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class kucunqianResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApi.huaxinMes.Location kucunqianResult;
        
        public kucunqianResponseBody() {
        }
        
        public kucunqianResponseBody(WebApi.huaxinMes.Location kucunqianResult) {
            this.kucunqianResult = kucunqianResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class kucunhouRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="kucunhou", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.kucunhouRequestBody Body;
        
        public kucunhouRequest() {
        }
        
        public kucunhouRequest(WebApi.huaxinMes.kucunhouRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class kucunhouRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string po_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rkdanhao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rkren;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string zuobiao;
        
        public kucunhouRequestBody() {
        }
        
        public kucunhouRequestBody(string po_no, string rkdanhao, string rkren, string zuobiao) {
            this.po_no = po_no;
            this.rkdanhao = rkdanhao;
            this.rkren = rkren;
            this.zuobiao = zuobiao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class kucunhouResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="kucunhouResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.kucunhouResponseBody Body;
        
        public kucunhouResponse() {
        }
        
        public kucunhouResponse(WebApi.huaxinMes.kucunhouResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class kucunhouResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kucunhouResult;
        
        public kucunhouResponseBody() {
        }
        
        public kucunhouResponseBody(string kucunhouResult) {
            this.kucunhouResult = kucunhouResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdingdanshujuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdingdanshuju", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.getdingdanshujuRequestBody Body;
        
        public getdingdanshujuRequest() {
        }
        
        public getdingdanshujuRequest(WebApi.huaxinMes.getdingdanshujuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getdingdanshujuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dingdan;
        
        public getdingdanshujuRequestBody() {
        }
        
        public getdingdanshujuRequestBody(string dingdan) {
            this.dingdan = dingdan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getdingdanshujuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getdingdanshujuResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.getdingdanshujuResponseBody Body;
        
        public getdingdanshujuResponse() {
        }
        
        public getdingdanshujuResponse(WebApi.huaxinMes.getdingdanshujuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getdingdanshujuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApi.huaxinMes.dingdan getdingdanshujuResult;
        
        public getdingdanshujuResponseBody() {
        }
        
        public getdingdanshujuResponseBody(WebApi.huaxinMes.dingdan getdingdanshujuResult) {
            this.getdingdanshujuResult = getdingdanshujuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getxianghaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getxianghao", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.getxianghaoRequestBody Body;
        
        public getxianghaoRequest() {
        }
        
        public getxianghaoRequest(WebApi.huaxinMes.getxianghaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getxianghaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dingdan;
        
        public getxianghaoRequestBody() {
        }
        
        public getxianghaoRequestBody(string dingdan) {
            this.dingdan = dingdan;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getxianghaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getxianghaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.getxianghaoResponseBody Body;
        
        public getxianghaoResponse() {
        }
        
        public getxianghaoResponse(WebApi.huaxinMes.getxianghaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getxianghaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getxianghaoResult;
        
        public getxianghaoResponseBody() {
        }
        
        public getxianghaoResponseBody(int getxianghaoResult) {
            this.getxianghaoResult = getxianghaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fahuohouRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fahuohou", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.fahuohouRequestBody Body;
        
        public fahuohouRequest() {
        }
        
        public fahuohouRequest(WebApi.huaxinMes.fahuohouRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fahuohouRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dingdan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xianghao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string gg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string po_no;
        
        public fahuohouRequestBody() {
        }
        
        public fahuohouRequestBody(string dingdan, string xianghao, string gg, string po_no) {
            this.dingdan = dingdan;
            this.xianghao = xianghao;
            this.gg = gg;
            this.po_no = po_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fahuohouResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fahuohouResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.fahuohouResponseBody Body;
        
        public fahuohouResponse() {
        }
        
        public fahuohouResponse(WebApi.huaxinMes.fahuohouResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fahuohouResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fahuohouResult;
        
        public fahuohouResponseBody() {
        }
        
        public fahuohouResponseBody(string fahuohouResult) {
            this.fahuohouResult = fahuohouResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getguangxianhaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getguangxianhao", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.getguangxianhaoRequestBody Body;
        
        public getguangxianhaoRequest() {
        }
        
        public getguangxianhaoRequest(WebApi.huaxinMes.getguangxianhaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getguangxianhaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pxfa;
        
        public getguangxianhaoRequestBody() {
        }
        
        public getguangxianhaoRequestBody(string pxfa) {
            this.pxfa = pxfa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getguangxianhaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getguangxianhaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.getguangxianhaoResponseBody Body;
        
        public getguangxianhaoResponse() {
        }
        
        public getguangxianhaoResponse(WebApi.huaxinMes.getguangxianhaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getguangxianhaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApi.huaxinMes.ArrayOfString getguangxianhaoResult;
        
        public getguangxianhaoResponseBody() {
        }
        
        public getguangxianhaoResponseBody(WebApi.huaxinMes.ArrayOfString getguangxianhaoResult) {
            this.getguangxianhaoResult = getguangxianhaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ISrkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ISrk", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.ISrkRequestBody Body;
        
        public ISrkRequest() {
        }
        
        public ISrkRequest(WebApi.huaxinMes.ISrkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ISrkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string po_no;
        
        public ISrkRequestBody() {
        }
        
        public ISrkRequestBody(string po_no) {
            this.po_no = po_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ISrkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ISrkResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.ISrkResponseBody Body;
        
        public ISrkResponse() {
        }
        
        public ISrkResponse(WebApi.huaxinMes.ISrkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ISrkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ISrkResult;
        
        public ISrkResponseBody() {
        }
        
        public ISrkResponseBody(bool ISrkResult) {
            this.ISrkResult = ISrkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ISchuhuoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ISchuhuo", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.ISchuhuoRequestBody Body;
        
        public ISchuhuoRequest() {
        }
        
        public ISchuhuoRequest(WebApi.huaxinMes.ISchuhuoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ISchuhuoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string po_no;
        
        public ISchuhuoRequestBody() {
        }
        
        public ISchuhuoRequestBody(string po_no) {
            this.po_no = po_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ISchuhuoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ISchuhuoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.ISchuhuoResponseBody Body;
        
        public ISchuhuoResponse() {
        }
        
        public ISchuhuoResponse(WebApi.huaxinMes.ISchuhuoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ISchuhuoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ISchuhuoResult;
        
        public ISchuhuoResponseBody() {
        }
        
        public ISchuhuoResponseBody(bool ISchuhuoResult) {
            this.ISchuhuoResult = ISchuhuoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ISlingliaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ISlingliao", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.ISlingliaoRequestBody Body;
        
        public ISlingliaoRequest() {
        }
        
        public ISlingliaoRequest(WebApi.huaxinMes.ISlingliaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ISlingliaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string po_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pq_no;
        
        public ISlingliaoRequestBody() {
        }
        
        public ISlingliaoRequestBody(string po_no, string pq_no) {
            this.po_no = po_no;
            this.pq_no = pq_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ISlingliaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ISlingliaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.ISlingliaoResponseBody Body;
        
        public ISlingliaoResponse() {
        }
        
        public ISlingliaoResponse(WebApi.huaxinMes.ISlingliaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ISlingliaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ISlingliaoResult;
        
        public ISlingliaoResponseBody() {
        }
        
        public ISlingliaoResponseBody(bool ISlingliaoResult) {
            this.ISlingliaoResult = ISlingliaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lingliaohouRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lingliaohou", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.lingliaohouRequestBody Body;
        
        public lingliaohouRequest() {
        }
        
        public lingliaohouRequest(WebApi.huaxinMes.lingliaohouRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lingliaohouRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string suilingliao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lldanhao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string llren;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string po_no;
        
        public lingliaohouRequestBody() {
        }
        
        public lingliaohouRequestBody(string suilingliao, string lldanhao, string llren, string po_no) {
            this.suilingliao = suilingliao;
            this.lldanhao = lldanhao;
            this.llren = llren;
            this.po_no = po_no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lingliaohouResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lingliaohouResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApi.huaxinMes.lingliaohouResponseBody Body;
        
        public lingliaohouResponse() {
        }
        
        public lingliaohouResponse(WebApi.huaxinMes.lingliaohouResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lingliaohouResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lingliaohouResult;
        
        public lingliaohouResponseBody() {
        }
        
        public lingliaohouResponseBody(string lingliaohouResult) {
            this.lingliaohouResult = lingliaohouResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LikuWSSoapChannel : WebApi.huaxinMes.LikuWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LikuWSSoapClient : System.ServiceModel.ClientBase<WebApi.huaxinMes.LikuWSSoap>, WebApi.huaxinMes.LikuWSSoap {
        
        public LikuWSSoapClient() {
        }
        
        public LikuWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LikuWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LikuWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LikuWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.kucunqianResponse WebApi.huaxinMes.LikuWSSoap.kucunqian(WebApi.huaxinMes.kucunqianRequest request) {
            return base.Channel.kucunqian(request);
        }
        
        public WebApi.huaxinMes.Location kucunqian(string po_no) {
            WebApi.huaxinMes.kucunqianRequest inValue = new WebApi.huaxinMes.kucunqianRequest();
            inValue.Body = new WebApi.huaxinMes.kucunqianRequestBody();
            inValue.Body.po_no = po_no;
            WebApi.huaxinMes.kucunqianResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).kucunqian(inValue);
            return retVal.Body.kucunqianResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.kucunqianResponse> WebApi.huaxinMes.LikuWSSoap.kucunqianAsync(WebApi.huaxinMes.kucunqianRequest request) {
            return base.Channel.kucunqianAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.kucunqianResponse> kucunqianAsync(string po_no) {
            WebApi.huaxinMes.kucunqianRequest inValue = new WebApi.huaxinMes.kucunqianRequest();
            inValue.Body = new WebApi.huaxinMes.kucunqianRequestBody();
            inValue.Body.po_no = po_no;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).kucunqianAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.kucunhouResponse WebApi.huaxinMes.LikuWSSoap.kucunhou(WebApi.huaxinMes.kucunhouRequest request) {
            return base.Channel.kucunhou(request);
        }
        
        public string kucunhou(string po_no, string rkdanhao, string rkren, string zuobiao) {
            WebApi.huaxinMes.kucunhouRequest inValue = new WebApi.huaxinMes.kucunhouRequest();
            inValue.Body = new WebApi.huaxinMes.kucunhouRequestBody();
            inValue.Body.po_no = po_no;
            inValue.Body.rkdanhao = rkdanhao;
            inValue.Body.rkren = rkren;
            inValue.Body.zuobiao = zuobiao;
            WebApi.huaxinMes.kucunhouResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).kucunhou(inValue);
            return retVal.Body.kucunhouResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.kucunhouResponse> WebApi.huaxinMes.LikuWSSoap.kucunhouAsync(WebApi.huaxinMes.kucunhouRequest request) {
            return base.Channel.kucunhouAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.kucunhouResponse> kucunhouAsync(string po_no, string rkdanhao, string rkren, string zuobiao) {
            WebApi.huaxinMes.kucunhouRequest inValue = new WebApi.huaxinMes.kucunhouRequest();
            inValue.Body = new WebApi.huaxinMes.kucunhouRequestBody();
            inValue.Body.po_no = po_no;
            inValue.Body.rkdanhao = rkdanhao;
            inValue.Body.rkren = rkren;
            inValue.Body.zuobiao = zuobiao;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).kucunhouAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.getdingdanshujuResponse WebApi.huaxinMes.LikuWSSoap.getdingdanshuju(WebApi.huaxinMes.getdingdanshujuRequest request) {
            return base.Channel.getdingdanshuju(request);
        }
        
        public WebApi.huaxinMes.dingdan getdingdanshuju(string dingdan) {
            WebApi.huaxinMes.getdingdanshujuRequest inValue = new WebApi.huaxinMes.getdingdanshujuRequest();
            inValue.Body = new WebApi.huaxinMes.getdingdanshujuRequestBody();
            inValue.Body.dingdan = dingdan;
            WebApi.huaxinMes.getdingdanshujuResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).getdingdanshuju(inValue);
            return retVal.Body.getdingdanshujuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.getdingdanshujuResponse> WebApi.huaxinMes.LikuWSSoap.getdingdanshujuAsync(WebApi.huaxinMes.getdingdanshujuRequest request) {
            return base.Channel.getdingdanshujuAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.getdingdanshujuResponse> getdingdanshujuAsync(string dingdan) {
            WebApi.huaxinMes.getdingdanshujuRequest inValue = new WebApi.huaxinMes.getdingdanshujuRequest();
            inValue.Body = new WebApi.huaxinMes.getdingdanshujuRequestBody();
            inValue.Body.dingdan = dingdan;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).getdingdanshujuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.getxianghaoResponse WebApi.huaxinMes.LikuWSSoap.getxianghao(WebApi.huaxinMes.getxianghaoRequest request) {
            return base.Channel.getxianghao(request);
        }
        
        public int getxianghao(string dingdan) {
            WebApi.huaxinMes.getxianghaoRequest inValue = new WebApi.huaxinMes.getxianghaoRequest();
            inValue.Body = new WebApi.huaxinMes.getxianghaoRequestBody();
            inValue.Body.dingdan = dingdan;
            WebApi.huaxinMes.getxianghaoResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).getxianghao(inValue);
            return retVal.Body.getxianghaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.getxianghaoResponse> WebApi.huaxinMes.LikuWSSoap.getxianghaoAsync(WebApi.huaxinMes.getxianghaoRequest request) {
            return base.Channel.getxianghaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.getxianghaoResponse> getxianghaoAsync(string dingdan) {
            WebApi.huaxinMes.getxianghaoRequest inValue = new WebApi.huaxinMes.getxianghaoRequest();
            inValue.Body = new WebApi.huaxinMes.getxianghaoRequestBody();
            inValue.Body.dingdan = dingdan;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).getxianghaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.fahuohouResponse WebApi.huaxinMes.LikuWSSoap.fahuohou(WebApi.huaxinMes.fahuohouRequest request) {
            return base.Channel.fahuohou(request);
        }
        
        public string fahuohou(string dingdan, string xianghao, string gg, string po_no) {
            WebApi.huaxinMes.fahuohouRequest inValue = new WebApi.huaxinMes.fahuohouRequest();
            inValue.Body = new WebApi.huaxinMes.fahuohouRequestBody();
            inValue.Body.dingdan = dingdan;
            inValue.Body.xianghao = xianghao;
            inValue.Body.gg = gg;
            inValue.Body.po_no = po_no;
            WebApi.huaxinMes.fahuohouResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).fahuohou(inValue);
            return retVal.Body.fahuohouResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.fahuohouResponse> WebApi.huaxinMes.LikuWSSoap.fahuohouAsync(WebApi.huaxinMes.fahuohouRequest request) {
            return base.Channel.fahuohouAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.fahuohouResponse> fahuohouAsync(string dingdan, string xianghao, string gg, string po_no) {
            WebApi.huaxinMes.fahuohouRequest inValue = new WebApi.huaxinMes.fahuohouRequest();
            inValue.Body = new WebApi.huaxinMes.fahuohouRequestBody();
            inValue.Body.dingdan = dingdan;
            inValue.Body.xianghao = xianghao;
            inValue.Body.gg = gg;
            inValue.Body.po_no = po_no;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).fahuohouAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.getguangxianhaoResponse WebApi.huaxinMes.LikuWSSoap.getguangxianhao(WebApi.huaxinMes.getguangxianhaoRequest request) {
            return base.Channel.getguangxianhao(request);
        }
        
        public WebApi.huaxinMes.ArrayOfString getguangxianhao(string pxfa) {
            WebApi.huaxinMes.getguangxianhaoRequest inValue = new WebApi.huaxinMes.getguangxianhaoRequest();
            inValue.Body = new WebApi.huaxinMes.getguangxianhaoRequestBody();
            inValue.Body.pxfa = pxfa;
            WebApi.huaxinMes.getguangxianhaoResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).getguangxianhao(inValue);
            return retVal.Body.getguangxianhaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.getguangxianhaoResponse> WebApi.huaxinMes.LikuWSSoap.getguangxianhaoAsync(WebApi.huaxinMes.getguangxianhaoRequest request) {
            return base.Channel.getguangxianhaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.getguangxianhaoResponse> getguangxianhaoAsync(string pxfa) {
            WebApi.huaxinMes.getguangxianhaoRequest inValue = new WebApi.huaxinMes.getguangxianhaoRequest();
            inValue.Body = new WebApi.huaxinMes.getguangxianhaoRequestBody();
            inValue.Body.pxfa = pxfa;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).getguangxianhaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.ISrkResponse WebApi.huaxinMes.LikuWSSoap.ISrk(WebApi.huaxinMes.ISrkRequest request) {
            return base.Channel.ISrk(request);
        }
        
        public bool ISrk(string po_no) {
            WebApi.huaxinMes.ISrkRequest inValue = new WebApi.huaxinMes.ISrkRequest();
            inValue.Body = new WebApi.huaxinMes.ISrkRequestBody();
            inValue.Body.po_no = po_no;
            WebApi.huaxinMes.ISrkResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).ISrk(inValue);
            return retVal.Body.ISrkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.ISrkResponse> WebApi.huaxinMes.LikuWSSoap.ISrkAsync(WebApi.huaxinMes.ISrkRequest request) {
            return base.Channel.ISrkAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.ISrkResponse> ISrkAsync(string po_no) {
            WebApi.huaxinMes.ISrkRequest inValue = new WebApi.huaxinMes.ISrkRequest();
            inValue.Body = new WebApi.huaxinMes.ISrkRequestBody();
            inValue.Body.po_no = po_no;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).ISrkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.ISchuhuoResponse WebApi.huaxinMes.LikuWSSoap.ISchuhuo(WebApi.huaxinMes.ISchuhuoRequest request) {
            return base.Channel.ISchuhuo(request);
        }
        
        public bool ISchuhuo(string po_no) {
            WebApi.huaxinMes.ISchuhuoRequest inValue = new WebApi.huaxinMes.ISchuhuoRequest();
            inValue.Body = new WebApi.huaxinMes.ISchuhuoRequestBody();
            inValue.Body.po_no = po_no;
            WebApi.huaxinMes.ISchuhuoResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).ISchuhuo(inValue);
            return retVal.Body.ISchuhuoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.ISchuhuoResponse> WebApi.huaxinMes.LikuWSSoap.ISchuhuoAsync(WebApi.huaxinMes.ISchuhuoRequest request) {
            return base.Channel.ISchuhuoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.ISchuhuoResponse> ISchuhuoAsync(string po_no) {
            WebApi.huaxinMes.ISchuhuoRequest inValue = new WebApi.huaxinMes.ISchuhuoRequest();
            inValue.Body = new WebApi.huaxinMes.ISchuhuoRequestBody();
            inValue.Body.po_no = po_no;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).ISchuhuoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.ISlingliaoResponse WebApi.huaxinMes.LikuWSSoap.ISlingliao(WebApi.huaxinMes.ISlingliaoRequest request) {
            return base.Channel.ISlingliao(request);
        }
        
        public bool ISlingliao(string po_no, string pq_no) {
            WebApi.huaxinMes.ISlingliaoRequest inValue = new WebApi.huaxinMes.ISlingliaoRequest();
            inValue.Body = new WebApi.huaxinMes.ISlingliaoRequestBody();
            inValue.Body.po_no = po_no;
            inValue.Body.pq_no = pq_no;
            WebApi.huaxinMes.ISlingliaoResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).ISlingliao(inValue);
            return retVal.Body.ISlingliaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.ISlingliaoResponse> WebApi.huaxinMes.LikuWSSoap.ISlingliaoAsync(WebApi.huaxinMes.ISlingliaoRequest request) {
            return base.Channel.ISlingliaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.ISlingliaoResponse> ISlingliaoAsync(string po_no, string pq_no) {
            WebApi.huaxinMes.ISlingliaoRequest inValue = new WebApi.huaxinMes.ISlingliaoRequest();
            inValue.Body = new WebApi.huaxinMes.ISlingliaoRequestBody();
            inValue.Body.po_no = po_no;
            inValue.Body.pq_no = pq_no;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).ISlingliaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApi.huaxinMes.lingliaohouResponse WebApi.huaxinMes.LikuWSSoap.lingliaohou(WebApi.huaxinMes.lingliaohouRequest request) {
            return base.Channel.lingliaohou(request);
        }
        
        public string lingliaohou(string suilingliao, string lldanhao, string llren, string po_no) {
            WebApi.huaxinMes.lingliaohouRequest inValue = new WebApi.huaxinMes.lingliaohouRequest();
            inValue.Body = new WebApi.huaxinMes.lingliaohouRequestBody();
            inValue.Body.suilingliao = suilingliao;
            inValue.Body.lldanhao = lldanhao;
            inValue.Body.llren = llren;
            inValue.Body.po_no = po_no;
            WebApi.huaxinMes.lingliaohouResponse retVal = ((WebApi.huaxinMes.LikuWSSoap)(this)).lingliaohou(inValue);
            return retVal.Body.lingliaohouResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApi.huaxinMes.lingliaohouResponse> WebApi.huaxinMes.LikuWSSoap.lingliaohouAsync(WebApi.huaxinMes.lingliaohouRequest request) {
            return base.Channel.lingliaohouAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApi.huaxinMes.lingliaohouResponse> lingliaohouAsync(string suilingliao, string lldanhao, string llren, string po_no) {
            WebApi.huaxinMes.lingliaohouRequest inValue = new WebApi.huaxinMes.lingliaohouRequest();
            inValue.Body = new WebApi.huaxinMes.lingliaohouRequestBody();
            inValue.Body.suilingliao = suilingliao;
            inValue.Body.lldanhao = lldanhao;
            inValue.Body.llren = llren;
            inValue.Body.po_no = po_no;
            return ((WebApi.huaxinMes.LikuWSSoap)(this)).lingliaohouAsync(inValue);
        }
    }
}
